
-- MySQL Script generated by MySQL Workbench
-- Sun May 29 16:08:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Site
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Site` DEFAULT CHARACTER SET utf8 ;
USE `Site` ;

-- -----------------------------------------------------
-- Table `Site`.`Anunciar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site`.`Anunciar` (
  `idAnunciar` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Idade` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Género` VARCHAR(45) NOT NULL,
  `Tamanho` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Anunciarcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnunciar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`.`Acerca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site`.`Acerca` (
  `idAcerca` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAcerca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Site.User (
  idUser INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  Anunciar_idAnunciar INT NOT NULL,
  Acerca_idAcerca INT NOT NULL,
  PRIMARY KEY (idUser, Anunciar_idAnunciar, Acerca_idAcerca),
  INDEX fk_User_Anunciar1_idx (Anunciar_idAnunciar ASC) ,
  INDEX fk_User_Acerca1_idx (Acerca_idAcerca ASC),
  CONSTRAINT fk_User_Anunciar1
    FOREIGN KEY (Anunciar_idAnunciar)
    REFERENCES Site.Anunciar (idAnunciar)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_User_Acerca1
    FOREIGN KEY (Acerca_idAcerca)
    REFERENCES Site.Acerca (idAcerca)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`.`Questionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site`.`Questionário` (
  `idQuestionário` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Idade` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Distrito` VARCHAR(45) NOT NULL,
  `Condições` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuestionário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`.`Animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site`.`Animais` (
  `idAnimais` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Raça` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Residência` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  `Questionário_idQuestionário` INT NOT NULL,
  PRIMARY KEY (`idAnimais`, `Questionário_idQuestionário`),
  INDEX `fk_Animais_User_idx` (`User_idUser` ASC), 
  INDEX `fk_Animais_Questionário1_idx` (`Questionário_idQuestionário` ASC),
  CONSTRAINT `fk_Animais_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Site`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animais_Questionário1`
    FOREIGN KEY (`Questionário_idQuestionário`)
    REFERENCES `Site`.`Questionário` (`idQuestionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`.`signup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site`.`signup` (
  `idsignup` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `confirmpass` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  `User_Anunciar_idAnunciar` INT NOT NULL,
  `User_Acerca_idAcerca` INT NOT NULL,
  PRIMARY KEY (`idsignup`),
  INDEX `fk_signup_User1_idx` (`User_idUser` ASC, `User_Anunciar_idAnunciar` ASC, `User_Acerca_idAcerca` ASC),
  CONSTRAINT `fk_signup_User1`
    FOREIGN KEY (`User_idUser` , `User_Anunciar_idAnunciar` , `User_Acerca_idAcerca`)
    REFERENCES `Site`.`User` (`idUser` , `Anunciar_idAnunciar` , `Acerca_idAcerca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
